name: Deploy

on:
  push:
    branches: [development]

jobs:
  deploy:
    name: Deploy to render
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to development
        uses: johnbeynon/render-deploy-action@v0.0.8

        with:
          service-id: ${{ secrets.SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }}